on:
  # push:
  workflow_dispatch:


jobs:

  squash-repo:
    runs-on: ubuntu-latest

    steps:
      - uses: fu1ny2t-3es/gi1-ac2io3s@squash-repo
        with:
          token: ${{ secrets.token }}
          auto: true
