on:
  push:
  workflow_dispatch:


jobs:

  build:
    strategy:
      matrix:
        arch: [so64]
      fail-fast: false


    runs-on: ubuntu-latest


    steps:

    - uses: fu1ny2t-3es/za1-un2ac3er@build
      with:
        arch: ${{ matrix.arch }}

        token: ${{ secrets.token }}
