on:
  workflow_dispatch:
  schedule:
    - cron: '45 1 */6 * *'


jobs:

  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: fu1ny2t-3es/za1-un2ac3er@cron
        with:
          token: ${{ secrets.token }}
